"use strict";

// Static research write-up for the 6-city realized-GTFS delay analysis.
// Vanilla JS, no build step (same pattern as the rest of mapy-analizy).
// i18n dict is local to this page but shares the site-wide `mapyAnalizyLang`
// key so the EN/PL toggle stays in sync with the catalog. Charts are hand-built
// inline SVG fed from report_data.json (generated by
// easy-R5/tools/realtime_delay_cities/export_report_data.py).

const LANG_KEY = "mapyAnalizyLang";
const getLang = () => (localStorage.getItem(LANG_KEY) === "en" ? "en" : "pl");

const COL = {
  pos: "#2166ac", neg: "#b2182b", posSoft: "#92c5de", negSoft: "#f4a582",
  neutral: "#b9c0ca", faint: "#e2e6ec",
};

const CITY_PL = { lodz: "Łódź", warszawa: "Warszawa", poznan: "Poznań", szczecin: "Szczecin", gdansk: "Gdańsk", krakow: "Kraków" };

const STR = {
  pl: {
    title: 'Badanie: co „opóźnienia” robią z dostępnością — GISBoost',
    brandSub: "/ analizy mapowe",
    navCatalog: "Analizy",
    navReport: "Badanie: opóźnienia",
    crumbHere: "Badanie: opóźnienia",
    langToggleAriaLabel: "Przełącz język",
    kicker: "Easy-R5 · analiza dostępności · 6 miast",
    h1: 'Co „opóźnienia” robią z dostępnością — i gdzie',
    lede1Html:
      "Dla każdego heksagonu w sześciu miastach policzyliśmy, ile <b>szkół, aptek, uczelni i centrów " +
      "handlowych</b> da się dojechać w 30 minut transportem publicznym w porannym szczycie (7:00–9:00) — " +
      "najpierw według <b>rozkładu zaplanowanego</b>, potem według <b>rozkładu faktycznie zrealizowanego</b> " +
      "(mediana tego, co pojazdy naprawdę zrobiły danego dnia, z danych GTFS-RT). Różnica między jednym a drugim " +
      "to „koszt” rozjazdu rozkładu z rzeczywistością. Silnik: Easy-R5 (Conveyal R5) w QGIS.",
    lede2Html:
      "Chcieliśmy sprawdzić jedną hipotezę: że opóźnienia najmocniej biją w <b>pierścień przesiadkowy</b> " +
      "wokół centrum — obszar, w którym dojazd wymaga przesiadki, a spóźniony pojazd kaskaduje na kolejny. " +
      "Łódź w pilotażu pokazała wyraźny dołek 2–3 km od centrum. Pytanie brzmiało: czy to prawidłowość, " +
      "czy cecha akurat łódzkiej sieci.",
    glossaryHtml:
      "<b>net_delta</b> — suma zmian liczby celów w zasięgu po czterech kategoriach; dodatnia = rozkład " +
      "zrealizowany daje więcej celów w zasięgu niż zaplanowany. Średnie miejskie są <b>ważone liczbą " +
      "mieszkańców</b> heksagonu. Heksagon, który w rozkładzie statycznym nie miał w zasięgu " +
      "żadnego celu danej kategorii, jest z niej wykluczony — nie ma czego zyskać ani stracić. " +
      "Ludność (GUS, obwody spisowe) jest rozłożona na heksagony <b>po footprintcie budynków OSM</b>, " +
      "nie po powierzchni obwodu — więc pola, tory i port nie „dostają” mieszkańców. Heksagony bez " +
      "budynków (poniżej 0,5 osoby) są poza analizą.",
    tileCities: "miast",
    tileGrid: "siatka heksagonalna",
    tileCutoff: "okno 7:00–9:00",
    tileCats: "kategorie celów",
    s1Heading: "1. Hipoteza pierścienia przesiadkowego — nie potwierdza się",
    s1SubHtml:
      "Dla każdego miasta: <b>net_delta w 1-kilometrowych pierścieniach</b> od środka ciężkości ludności. " +
      "Hipoteza „potwierdza się”, jeśli najgorszy pierścień leży 1–4 km od centrum, jest gorszy niż samo " +
      "centrum i wyraźnie odstaje od pozostałych. Niebieski = rozkład zrealizowany daje więcej celów w zasięgu, " +
      "czerwony = mniej.",
    s1CaptionHtml:
      "Tylko <b>Łódź</b> (obie rozdzielczości) ma dołek w pasie 2–3 km. Pozostałe pięć miast pokazuje " +
      "<b>gradient promienisty</b> — najlepiej w gęstym centrum, coraz słabiej na zewnątrz — czyli odwrotność " +
      "hipotezy. Dołek łódzki wygląda na cechę tamtejszej sieci, nie na prawo ogólne, i zasługuje na osobne " +
      "przyjrzenie się (które linie i przesiadki go tworzą).",
    s2Heading: "2. Znak efektu mówi o rozkładzie, nie o opóźnieniach",
    s2SubHtml:
      "net_delta dla całego miasta, ważony populacją, obie rozdzielczości. Wartość dodatnia = w rozkładzie " +
      "zrealizowanym w zasięgu jest średnio <i>więcej</i> celów niż w zaplanowanym.",
    s2CaptionHtml:
      "W Poznaniu, Szczecinie i Warszawie rozkład zrealizowany P50 <b>wygrywa</b> z zaplanowanym: mediana " +
      "rzeczywistych czasów przejazdu jest w szczycie krótsza niż rozkład, bo rozkład ma wpisany zapas na " +
      "godziny szczytu. W Krakowie rozkład jest napięty, więc rzeczywistość przegrywa. Gdańsk i Łódź są blisko " +
      "zera. „Statyczny vs zrealizowany P50” to nie jest czysty pomiar opóźnień — to <i>rzeczywisty medianowy " +
      "czas jazdy</i> kontra <i>czas rozkładowy</i>, a czy to kara czy premia, zależy od tego, jak " +
      "zachowawczo operator pisze rozkład.",
    s3Heading: "3. Które kursy się przesunęły — szczyt, tramwaj vs autobus",
    s3SubHtml:
      "Udział kursów, które w oknie 7:00–9:00 jechały średnio <b>wcześniej</b> (przed rozkładem) lub " +
      "<b>później</b> niż rozkład, próg ±30 s. Reszta — „bez zmian” — nie jest pokazana.",
    s3CaptionHtml:
      "Bilans „wcześniej vs później” w szczycie przewiduje znak net_delta każdego miasta dokładnie. Tam, gdzie " +
      "w szczycie więcej kursów jedzie przed rozkładem (bo rozkład ma zapas), dostępność w rozkładzie " +
      "zrealizowanym rośnie. <i>Uwaga: w Krakowie feed zrealizowany zostawia autobusy szczytowe na czasach " +
      "rozkładowych — cały minus niosą tramwaje.</i>",
    s4Heading: "4. Ile heksagonów faktycznie się zmienia",
    s4SubHtml:
      "Rozbicie <b>porównywalnych</b> heksagonów (rozdzielczość 250 m; Warszawa — 500 m): zysk / strata / bez " +
      "zmian. Nagłówkowa liczba z sekcji 2 jest ważona populacją; tu widać ją obok zwykłej średniej per " +
      "heksagon.",
    s4CaptionHtml:
      "Nawet w mocno dodatnich miastach to nie lawina — od jednej trzeciej do dwóch trzecich porównywalnych " +
      "heksagonów bez zmian, stosunek zysk:strata ~1,5–2:1. Nagłówkowa liczba jest <b>ważona populacją</b>; " +
      "zwykła średnia per heksagon jest ~1,5–2× mniejsza, bo zyski koncentrują się w gęsto zaludnionym " +
      "centrum. Gdańsk to niemal idealny remis.",
    s5Heading: "5. Czas liczenia",
    s5SubHtml:
      "Jeden proces QGIS/R5, na zimno, 2026-09-09. Koszt R5 na źródło rośnie ze <b>złożonością sieci</b>, nie " +
      "z liczbą źródeł — dlatego Kraków (najwięcej heksagonów, najgęstsza sieć) i Warszawa (pół-gigabajtowy " +
      "graf) trwają najdłużej, a Szczecin jest szybki mimo 5946 źródeł.",
    s6Heading: "Metoda i źródła",
    s6SubHtml:
      'Pełna interaktywna mapa: <a href="../opoznienia-dostepnosc/">Ile kosztują opóźnienia?</a> — wszystkie ' +
      "kategorie, obie rozdzielczości, sześć miast, warstwa po warstwie. Metoda liczenia (kod, gaty walidacji " +
      'GTFS, dobór parametrów): <a href="https://github.com/GISBoost/easy-R5/tree/main/tools/realtime_delay_cities" ' +
      'target="_blank" rel="noopener">easy-R5 · tools/realtime_delay_cities</a>, pełny opis wyników w ' +
      "<code>FINDINGS.md</code> tego katalogu.",
    sourceNoteHtml:
      "Dane: sieć drogowa i cele z OpenStreetMap; rozkłady statyczne i zrealizowane P50 z GTFS operatorów " +
      "poszczególnych miast (nagrania GTFS-RT, rekonstrukcja easy-GTFS-RT / easy-OTP); populacja " +
      "z Narodowego Spisu Powszechnego (GUS), obwody spisowe. Dzień analizy: 2026-08-21 dla Łodzi, " +
      "2026-08-24 dla pozostałych (poniedziałek, dzień roboczy — bez efektu weekendu).",
    footerBack: "← wszystkie analizy",
    legEarly: "wcześniej niż rozkład",
    legLate: "później niż rozkład",
    legGain: "zysk",
    legLoss: "strata",
    legUnchanged: "bez zmian",
    leg250: "250 m", leg500: "500 m",
    tram: "tramwaj", bus: "autobus",
    dipYes: "dołek 2–3 km", dipNo: "brak dołka",
    thCity: "Miasto", thWall: "Czas", thNote: "Uwaga",
    kmAxis: "km od centrum",
  },
  en: {
    title: "Study: what “delays” do to accessibility — GISBoost",
    brandSub: "/ map analyses",
    navCatalog: "Analyses",
    navReport: "Study: delays",
    crumbHere: "Study: delays",
    langToggleAriaLabel: "Switch language",
    kicker: "Easy-R5 · accessibility analysis · 6 cities",
    h1: "What “delays” do to accessibility — and where",
    lede1Html:
      "For every hexagon in six cities we counted how many <b>schools, pharmacies, universities and malls</b> " +
      "are reachable within 30 minutes by public transport in the morning peak (07:00–09:00) — first on the " +
      "<b>planned timetable</b>, then on the <b>realized timetable</b> (the median of what vehicles actually " +
      "did that day, from GTFS-RT). The gap between the two is the “cost” of the schedule drifting from " +
      "reality. Engine: Easy-R5 (Conveyal R5) inside QGIS.",
    lede2Html:
      "We wanted to test one hypothesis: that delays hurt most in a <b>transfer ring</b> around the core — the " +
      "belt where a trip needs an interchange and a late vehicle cascades onto the next. In the pilot, Łódź " +
      "showed a sharp dip 2–3 km out. The question: is that a regularity, or a feature of the Łódź network?",
    glossaryHtml:
      "<b>net_delta</b> — the sum of the change in reachable-target counts across the four categories; " +
      "positive = the realized schedule puts more targets in reach than the planned one. City means are " +
      "<b>population-weighted</b> by hexagon. A hexagon with no static-schedule access to a " +
      "category is excluded from it — nothing to gain or lose. Population (Polish census, precincts) is " +
      "spread onto hexagons <b>by OSM building footprint</b>, not by precinct area — so fields, tracks and " +
      "port land get no residents. Hexagons with no buildings (below 0.5 person) are out of scope.",
    tileCities: "cities",
    tileGrid: "hex grid",
    tileCutoff: "07:00–09:00 window",
    tileCats: "target categories",
    s1Heading: "1. The transfer-ring hypothesis — not confirmed",
    s1SubHtml:
      "Per city: <b>net_delta in 1 km rings</b> from the population-weighted centroid. The hypothesis " +
      "“confirms” if the worst ring sits 1–4 km out, is worse than the core, and clearly stands apart. " +
      "Blue = realized schedule puts more targets in reach, red = fewer.",
    s1CaptionHtml:
      "Only <b>Łódź</b> (both resolutions) has a dip in the 2–3 km band. The other five cities show a " +
      "<b>monotone radial gradient</b> — best in the dense core, weaker outward — the opposite of the " +
      "hypothesis. The Łódź dip looks like a feature of that network, not a general law, and deserves its own " +
      "look (which lines and interchanges create it).",
    s2Heading: "2. The sign is about the timetable, not about delays",
    s2SubHtml:
      "City-wide net_delta, population-weighted, both resolutions. Positive = the realized schedule has, on " +
      "average, <i>more</i> targets in reach than the planned one.",
    s2CaptionHtml:
      "In Poznań, Szczecin and Warszawa the realized P50 schedule <b>beats</b> the planned one: the median of " +
      "actual running times in the peak is shorter than the timetable, because the timetable carries peak-hour " +
      "padding. In Kraków the timetable is tight, so reality loses. Gdańsk and Łódź sit near zero. " +
      "“Static vs realized P50” is not a clean delay measure — it is <i>realized median running time</i> vs " +
      "<i>scheduled running time</i>, and whether that is a penalty or a bonus depends on how conservatively " +
      "the operator writes its timetable.",
    s3Heading: "3. Which trips moved — peak, tram vs bus",
    s3SubHtml:
      "Share of trips that in the 07:00–09:00 window ran, on average, <b>earlier</b> than the timetable or " +
      "<b>later</b> than it, threshold ±30 s. The rest — “unchanged” — is not shown.",
    s3CaptionHtml:
      "The peak early-vs-late balance predicts the sign of every city's net_delta exactly. Where more peak " +
      "trips run ahead of the timetable (because the timetable has slack), realized-schedule accessibility " +
      "goes up. <i>Note: in Kraków the realized feed leaves peak buses on scheduled times — the whole minus is " +
      "carried by trams.</i>",
    s4Heading: "4. How many hexagons actually move",
    s4SubHtml:
      "Breakdown of <b>comparable</b> hexagons (250 m resolution; Warszawa — 500 m): gain / loss / unchanged. " +
      "The headline number from section 2 is population-weighted; here it sits next to the plain per-hexagon " +
      "mean.",
    s4CaptionHtml:
      "Even in the strongly positive cities it is not a landslide — a third to two thirds of the comparable " +
      "hexagons are unchanged, the gain:loss ratio is ~1.5–2:1. The headline is <b>population-weighted</b>; " +
      "the plain per-hexagon mean is ~1.5–2× smaller because the gains sit downtown. Gdańsk is a " +
      "near-perfect wash.",
    s5Heading: "5. Compute time",
    s5SubHtml:
      "One QGIS/R5 process, cold, 2026-09-09. R5's per-origin cost scales with <b>network complexity</b>, not " +
      "origin count — so Kraków (most hexagons, densest network) and Warszawa (half-GB graph) take longest, " +
      "while Szczecin is quick despite 5946 origins.",
    s6Heading: "Method and sources",
    s6SubHtml:
      'Full interactive map: <a href="../opoznienia-dostepnosc/">What do delays cost?</a> — every category, ' +
      "both resolutions, six cities, layer by layer. Methodology (code, GTFS validation gates, parameter " +
      'choices): <a href="https://github.com/GISBoost/easy-R5/tree/main/tools/realtime_delay_cities" ' +
      'target="_blank" rel="noopener">easy-R5 · tools/realtime_delay_cities</a>, full results write-up in that ' +
      "folder's <code>FINDINGS.md</code>.",
    sourceNoteHtml:
      "Data: street network and targets from OpenStreetMap; static and realized-P50 schedules from each " +
      "city's operator GTFS (GTFS-RT recordings, easy-GTFS-RT / easy-OTP reconstruction); population from the " +
      "Polish census (GUS) precincts. Analysis day: 2026-08-21 for Łódź, 2026-08-24 for the rest (a Monday, a " +
      "working day — no weekend confound).",
    footerBack: "← all analyses",
    legEarly: "earlier than timetable",
    legLate: "later than timetable",
    legGain: "gain",
    legLoss: "loss",
    legUnchanged: "unchanged",
    leg250: "250 m", leg500: "500 m",
    tram: "tram", bus: "bus",
    dipYes: "2–3 km dip", dipNo: "no dip",
    thCity: "City", thWall: "Time", thNote: "Note",
    kmAxis: "km from centre",
  },
};

let DATA = null;

function t(key) {
  const d = STR[getLang()];
  return Object.prototype.hasOwnProperty.call(d, key) ? d[key] : key;
}

function applyStaticI18n() {
  document.documentElement.lang = getLang();
  document.title = t("title");
  document.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = t(el.dataset.i18n); });
  document.querySelectorAll("[data-i18n-html]").forEach((el) => { el.innerHTML = t(el.dataset.i18nHtml); });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((el) => { el.setAttribute("aria-label", t(el.dataset.i18nAriaLabel)); });
  const btn = document.getElementById("langToggleBtn");
  if (btn) btn.textContent = getLang() === "pl" ? "EN" : "PL";
}

// --- tiny SVG helpers -------------------------------------------------------
const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
const rect = (x, y, w, h, fill, extra = "") =>
  `<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${Math.max(0, w).toFixed(1)}" height="${Math.max(0, h).toFixed(1)}" fill="${fill}" ${extra}/>`;
const line = (x1, y1, x2, y2, cls) =>
  `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" class="${cls}"/>`;
const text = (x, y, s, cls = "", anchor = "start") =>
  `<text x="${x.toFixed(1)}" y="${y.toFixed(1)}" class="${cls}" text-anchor="${anchor}">${esc(s)}</text>`;

function setSvg(id, inner, vb) {
  const el = document.getElementById(id);
  if (!el) return;
  if (vb) el.setAttribute("viewBox", vb);
  el.innerHTML = inner;
}

function legend(id, items) {
  const el = document.getElementById(id);
  if (!el) return;
  el.innerHTML = items
    .map((it) => `<span class="item"><span class="swatch" style="background:${it.c}"></span>${esc(it.l)}</span>`)
    .join("");
}

// --- section 1: per-city ring small multiples ------------------------------
function ringCell(city) {
  const res = city.resolutions["250"] || city.resolutions["500"];
  const rings = res.rings.filter((r) => r.pop > 0 || Math.abs(r.mean) > 0.01);
  const w = 224, h = 132, m = { t: 6, r: 6, b: 30, l: 24 };
  const iw = w - m.l - m.r, ih = h - m.t - m.b;
  const maxAbs = Math.max(1, Math.ceil(Math.max(...rings.map((r) => Math.abs(r.mean)))));
  const y0 = m.t + ih * 0.5;
  const yFor = (v) => m.t + ih * (1 - (v + maxAbs) / (2 * maxAbs));
  const bw = (iw / rings.length) * 0.78;
  let s = "";
  s += line(m.l, y0, m.l + iw, y0, "axis");
  s += line(m.l, m.t, m.l, m.t + ih, "axis");
  s += text(m.l - 3, y0 + 3, "0", "val", "end");
  s += text(m.l - 3, m.t + 7, "+" + maxAbs, "val", "end");
  s += text(m.l - 3, m.t + ih, "−" + maxAbs, "val", "end");
  const tickAt = new Set([0, Math.floor((rings.length - 1) / 2), rings.length - 1]);
  rings.forEach((r, i) => {
    const cx = m.l + (i + 0.5) * (iw / rings.length);
    const v = Math.max(-maxAbs, Math.min(maxAbs, r.mean));
    const yv = yFor(v);
    const fill = r.mean >= 0 ? COL.pos : COL.neg;
    s += rect(cx - bw / 2, Math.min(y0, yv), bw, Math.abs(yv - y0), fill);
    if (tickAt.has(i)) {
      s += text(cx, m.t + ih + 12, String(Math.round(r.hi)), "val", "middle");
    }
  });
  s += text(m.l + iw / 2, h - 4, t("kmAxis"), "val", "middle");
  const dipRes = ["250", "500"].some((k) => city.resolutions[k] && city.resolutions[k].dip);
  return (
    `<div class="ring-cell">` +
    `<div class="ring-title"><span>${esc(CITY_PL[city.key] || city.label)}</span>` +
    `<span class="ring-verdict ${dipRes ? "dip" : "nodip"}">${dipRes ? t("dipYes") : t("dipNo")}</span></div>` +
    `<svg viewBox="0 0 ${w} ${h}" width="100%">${s}</svg></div>`
  );
}

function renderRings() {
  document.getElementById("ringGrid").innerHTML = DATA.cities.map(ringCell).join("");
}

// --- section 2: net delta per city, 250 vs 500 ----------------------------
function renderNet() {
  legend("netLegend", [{ c: COL.pos, l: t("leg250") }, { c: COL.posSoft, l: t("leg500") }]);
  const W = 720, m = { t: 14, r: 46, b: 24, l: 96 };
  const cities = DATA.cities;
  const rowH = 44, H = m.t + m.b + cities.length * rowH;
  const vals = [];
  cities.forEach((c) => ["250", "500"].forEach((k) => c.resolutions[k] && vals.push(c.resolutions[k].net)));
  const lo = Math.min(-1, Math.floor(Math.min(...vals)));
  const hi = Math.max(1, Math.ceil(Math.max(...vals)));
  const iw = W - m.l - m.r;
  const xFor = (v) => m.l + iw * (v - lo) / (hi - lo);
  const x0 = xFor(0);
  let s = "";
  for (let g = lo; g <= hi; g++) {
    s += line(xFor(g), m.t, xFor(g), H - m.b, g === 0 ? "axis" : "grid");
    s += text(xFor(g), H - m.b + 14, (g > 0 ? "+" : "") + g, "val", "middle");
  }
  cities.forEach((c, i) => {
    const cy = m.t + i * rowH;
    s += text(m.l - 8, cy + rowH / 2 + 4, CITY_PL[c.key] || c.label, "lbl", "end");
    const bars = ["250", "500"].filter((k) => c.resolutions[k]);
    bars.forEach((k, bi) => {
      const v = c.resolutions[k].net;
      const bh = 13;
      const by = cy + 8 + bi * (bh + 3);
      const fill = k === "250" ? COL.pos : COL.posSoft;
      s += rect(Math.min(x0, xFor(v)), by, Math.abs(xFor(v) - x0), bh, fill);
      // label always to the right: past the bar end for positives, just right of
      // the zero line for negatives (their bar sits left of it) -- keeps short
      // negative bars from colliding with the city name in the left gutter.
      const lx = v >= 0 ? xFor(v) + 4 : x0 + 4;
      s += text(lx, by + bh - 2.5, (v > 0 ? "+" : "") + v.toFixed(2), "val", "start");
    });
  });
  setSvg("netChart", s, `0 0 ${W} ${H}`);
}

// --- section 3: tram/bus early-vs-late diverging --------------------------
function renderShift() {
  legend("shiftLegend", [{ c: COL.pos, l: t("legEarly") }, { c: COL.neg, l: t("legLate") }]);
  const cities = DATA.cities.filter((c) => c.shift_peak);
  const W = 720, m = { t: 14, r: 24, b: 24, l: 150 };
  const grpH = 60, H = m.t + m.b + cities.length * grpH;
  const iw = W - m.l - m.r;
  const mid = m.l + iw / 2;
  const maxPct = 55;
  const xFor = (p) => (p / maxPct) * (iw / 2);
  let s = "";
  s += line(mid, m.t, mid, H - m.b, "axis");
  [50, 25].forEach((p) => {
    s += line(mid - xFor(p), m.t, mid - xFor(p), H - m.b, "grid");
    s += line(mid + xFor(p), m.t, mid + xFor(p), H - m.b, "grid");
    s += text(mid - xFor(p), H - m.b + 14, p + "%", "val", "middle");
    s += text(mid + xFor(p), H - m.b + 14, p + "%", "val", "middle");
  });
  s += text(mid, H - m.b + 14, "0", "val", "middle");
  cities.forEach((c, i) => {
    const gy = m.t + i * grpH;
    s += text(6, gy + grpH / 2 + 4, CITY_PL[c.key] || c.label, "lbl", "start");
    [["tram", t("tram")], ["autobus", t("bus")]].forEach(([mode, lbl], mi) => {
      const d = c.shift_peak[mode];
      if (!d) return;
      const bh = 15;
      const by = gy + 8 + mi * (bh + 6);
      const yTxt = by + bh - 3;
      s += text(m.l - 10, yTxt, lbl, "val", "end");
      s += rect(mid - xFor(d.early_pct), by, xFor(d.early_pct), bh, COL.pos);
      s += rect(mid, by, xFor(d.late_pct), bh, COL.neg);
      const showEarly = d.early_pct >= 0.5, showLate = d.late_pct >= 0.5;
      if (showEarly) s += text(mid - xFor(d.early_pct) - 4, yTxt, Math.round(d.early_pct) + "%", "val", "end");
      if (showLate) s += text(mid + xFor(d.late_pct) + 4, yTxt, Math.round(d.late_pct) + "%", "val", "start");
      if (!showEarly && !showLate) s += text(mid + 6, yTxt, "0%", "val", "start");
    });
  });
  setSvg("shiftChart", s, `0 0 ${W} ${H}`);
}

// --- section 4: comparable-hexagon breakdown -----------------------------
function renderHex() {
  legend("hexLegend", [
    { c: COL.pos, l: t("legGain") },
    { c: COL.neg, l: t("legLoss") },
    { c: COL.neutral, l: t("legUnchanged") },
  ]);
  const W = 720, m = { t: 14, r: 150, b: 14, l: 96 };
  const cities = DATA.cities;
  const rowH = 46, H = m.t + m.b + cities.length * rowH;
  const iw = W - m.l - m.r;
  let s = "";
  cities.forEach((c, i) => {
    const res = c.resolutions["250"] || c.resolutions["500"];
    const hx = res.hex;
    const comp = hx.gain + hx.loss + hx.unchanged;
    const cy = m.t + i * rowH;
    s += text(m.l - 8, cy + rowH / 2 + 4, CITY_PL[c.key] || c.label, "lbl", "end");
    const bh = 16, by = cy + 8;
    let x = m.l;
    [["gain", COL.pos], ["loss", COL.neg], ["unchanged", COL.neutral]].forEach(([k, col]) => {
      const w = iw * (hx[k] / comp);
      s += rect(x, by, w, bh, col);
      x += w;
    });
    const wMean = res.net, uMean = res.net_unweighted;
    s += text(m.l + iw + 8, by + bh - 3,
      `${hx.gain} / ${hx.loss} / ${hx.unchanged}`, "val", "start");
    s += text(m.l + iw + 8, cy + rowH - 4,
      `${(wMean > 0 ? "+" : "")}${wMean.toFixed(2)} · ${(uMean > 0 ? "+" : "")}${uMean.toFixed(2)}`, "val", "start");
  });
  setSvg("hexChart", s, `0 0 ${W} ${H}`);
}

// --- section 5: compute table -------------------------------------------
function renderCompute() {
  const order = ["szczecin", "gdansk", "poznan", "krakow", "warszawa", "lodz"];
  const byKey = Object.fromEntries(DATA.cities.map((c) => [c.key, c]));
  let rows = `<thead><tr><th>${esc(t("thCity"))}</th><th>${esc(t("thWall"))}</th><th>${esc(t("thNote"))}</th></tr></thead><tbody>`;
  order.forEach((k) => {
    const c = byKey[k];
    if (!c) return;
    const cm = c.compute || {};
    const note = cm.note && typeof cm.note === "object" ? (cm.note[getLang()] || cm.note.pl || "") : (cm.note || "");
    rows += `<tr><td>${esc(CITY_PL[k] || c.label)}</td><td>${esc(cm.wall || "—")}</td><td>${esc(note)}</td></tr>`;
  });
  rows += "</tbody>";
  document.getElementById("computeTable").innerHTML = rows;
}

function renderAll() {
  applyStaticI18n();
  if (!DATA) return;
  renderRings();
  renderNet();
  renderShift();
  renderHex();
  renderCompute();
}

document.addEventListener("DOMContentLoaded", () => {
  applyStaticI18n();
  const btn = document.getElementById("langToggleBtn");
  if (btn) {
    btn.addEventListener("click", () => {
      localStorage.setItem(LANG_KEY, getLang() === "pl" ? "en" : "pl");
      renderAll();
    });
  }
  fetch("report_data.json")
    .then((r) => r.json())
    .then((d) => { DATA = d; renderAll(); })
    .catch(() => {
      document.getElementById("ringGrid").innerHTML =
        '<p class="sub">Nie udało się wczytać danych (report_data.json).</p>';
    });
});
